---
- hosts: all
  remote_user: root

  roles:
     - docker-NC

  vars:
    password: $1$SomeSalt$08FKx76sNa/FGLYNGmoFI0
    target_zone: 'Europe/Paris'

  tasks:
    - name: Create guest user "zenguest"
      user: name=zenguest group=docker shell=/bin/bash password={{password}}

    - name: Check current timezone
      shell: cat /etc/timezone
      register: current_zone

    - name: Set timezone variables
      copy: content={{target_zone}}
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      when: current_zone.stdout != target_zone
      notify:
        - update timezone

  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata